pipeline:
  identifier: Build_mylon810_repo_template_1778281347039
  name: Build repo-template
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1778281078846
        repoName: mylon810/repo-template
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
